name: streamable
version: 0.0.5
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
description: a library of helpful custom stream candies
homepage: http://influx.github.com/pipes.dart
dependencies:
  ds: any
  hub: any
  invocable: any
  statemanager: any
