name: streamable
version: 0.3.1
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
description: provides streaming api based on nodelists
homepage: http://influx.github.com/streamable.dart
dependencies:
  ds: any
  hub: any
