name: streamable
version: 0.3.9
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
description: provides a mixable streaming api based on nodelists 
homepage: http://influx.github.com/streamable.dart
dependencies:
  ds: any
  hub: any
