name: streamable
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
version: 0.1.3
homepage: http://influx.github.com/streamable.dart
description: a library of helpful custom stream candies
dependencies:
  ds: any
  hub: any
