name: streamable
version: 0.1.2
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
description: a library of helpful custom stream candies
homepage: http://influx.github.com/streamable.dart
dependencies:
  ds: any
  hub: any
